spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.url=${DB_URL:jdbc:h2:mem:health_db}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

